[".config/bat/themes"]
type = "archive"
url = "https://github.com/catppuccin/bat/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 2
include = ["*/themes/*.tmTheme"]
refreshPeriod = "168h"

[".config/btop/themes"]
type = "archive"
url = "https://github.com/catppuccin/btop/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 2
include = ["*/themes/*.theme"]
refreshPeriod = "168h"

[".config/gitui/themes"]
type = "archive"
url = "https://github.com/catppuccin/gitui/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 2
include = ["*/themes/catppuccin-*.ron"]
refreshPeriod = "168h"

[".config/yazi/catppuccin"]
type = "archive"
url = "https://github.com/catppuccin/yazi/archive/refs/heads/main.tar.gz"
exact = true
stripComponents = 3
include = ["*/themes/*/*.toml"]
refreshPeriod = "168h"
