[formatter.shell]
command = "bunx"
options = ["shfmt", "-w", "-i", "2", "-ci"]
includes = ["*.sh", "*.zsh", "*.bash", "*.sh.tmpl"]

[formatter.toml]
command = "bunx"
options = ["taplo", "format"]
includes = ["*.toml"]

[formatter.markdown]
command = "bunx"
options = ["prettier", "--write"]
includes = ["*.md"]
