[formatter.shell]
command = "shfmt"
options = ["-w", "-i", "2", "-ci"]
includes = ["*.sh", "*.zsh", "*.bash", "*.sh.tmpl"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.markdown]
command = "prettier"
options = ["--write"]
includes = ["*.md"]
